### PR TITLE
Add custom controller name to resources in routing

### PR DESCRIPTION
**Pull request by nsanta**
This is a 🙋‍♂️ feature or enhancement.
This is a 🧐 documentation change.

- [x] I've added tests (if it's a bug, feature or enhancement)
- [x] I've adjusted the documentation (if it's a feature or enhancement)
- [x] The test suite passes (run `bundle exec rspec` to verify this)

## Summary

Actually the `resources` method for handle the routing is inflexible. There is no mechanism to provide the controller to be used for creates the proper routes for a resource.

I'm introducing an option in `resources` method which, for now, support the controller option. This is an enhancement for give resource path that is different from the controller.

Example:

`resources 'api/v1/articles', controller: 'posts'`.

### CODE REVIEW

**Comment by tongueroo** [comment]
Thank you so much for taking the time to submit a pull request. Took some time to read through the rails routes current features. Unsure about this interface, think going to pass on this one. 👌

**Comment by nsanta** [comment]
@tongueroo 

This interface is supported by Rails already: https://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use

I made this PR because the routing system is not flexible as I want. So decided to improve it a little bit the capabilities of `resources` functionality like define the 'controller' to use for a resource route definition. While it looks a workaround and does not offers all the Rails routes capabilities, solve some problems related to how you define the resources vs how you organize the controllers (including controller namespaces).

Example (source code extracted from a project that I'm working on):

```
namespace :v1 do
    resources :items, controller: 'v1/items'

    resources :invoices, controller: 'v1/invoices'
    resources :invoices_items, controller: 'v1/invoices/items'
 end
```

Thoughts?

**Comment by tongueroo** [comment]
Interesting. Will take a look in a bit 👌

**Comment by tongueroo** [comment]
Done #318 Released in [v2.0.0](https://github.com/tongueroo/jets/blob/master/CHANGELOG.md) 🎉

Docs here: https://rubyonjets.com/docs/routing/guide/

**Pull request closed without merging**
