### PR TITLE
add jets destroy as opposite of generator

### PR DESCRIPTION
**Pull request by aoozdemir**
This is a 🙋‍♂️ feature or enhancement.
This is a 🧐 documentation change.

- [x] I've added tests (if it's a bug, feature or enhancement)
  - The thing is, I didn't know how to write specs for this, as I couldn't find the corresponding specs for generate. I assume it'll be ok since jets piggy back this from rails.
- [x] I've adjusted the documentation (if it's a feature or enhancement)
- [x] The test suite passes (run `bundle exec rspec` to verify this)

## Summary

This PR adds `jets destroy` command. Basically, the opposite of `jets generate`. The command calls `behavior: :revoke` instead of `:invoke`.

## Context

See [#rails-destroy](https://guides.rubyonrails.org/command_line.html#rails-destroy).

### Screenshot

screenshot at feb 26 02-33-12

## Version Changes

`TINY` will suffice.

### CODE REVIEW

**Comment by nsanta** [comment]
Neat! 👍

**Comment by aoozdemir** [comment]
@tongueroo any suggestion for specs?

**Comment by tongueroo** [comment]
@aoozdemir For specs, maybe a CLI spec that does a noop? So the CLI portion is tested. Not a biggie though.

One thing with this PR is that these 2 classes are nearly identical:

* https://github.com/aoozdemir/jets/blob/master/lib/jets/destroy.rb
* https://github.com/aoozdemir/jets/blob/master/lib/jets/generator.rb

```diff
$ diff lib/jets/{generator,destroy}.rb                               
2c2
< class Jets::Generator
---
> class Jets::Destroy
17c17
<     Rails::Generators.invoke(@generator, @args, behavior: :invoke, destination_root: Jets.root)
---
>     Rails::Generators.invoke(@generator, @args, behavior: :revoke, destination_root: Jets.root)
```

So a bit of duplication here. Should be only one `Generator` class with a parameter.

Another thing is that `jets destroy` and `jets delete` are too similar. Will be confusing to remember. Understand that it's called `rails destroy` but rails doesn't have deploy and delete concepts, so that's probably why it's not an issue for it. Think it makes sense to not follow rails here. Thinking let's go with  `jets degenerate` instead; it feels clearer.

**Comment by aoozdemir** [comment]
@tongueroo thanks for the reply! `degenerate` makes sense. 👍I'll dry the classes and do the appropriate changes for `degenerate`, then make a commit.

**Comment by aoozdemir** [comment]
@tongueroo hi! sorry this took so long 🙂 I've added a simple cli spec here https://github.com/tongueroo/jets/pull/208/commits/3f697eac89d5b6bb836d7843ebd2e6f3c89262b3.

**Comment by tongueroo** [comment]
@aoozdemir Yes! So much better. Felt the same thing but been haven't had time to put thoughts together explaining it. Happy you figured it out!  Cheers, Tung

**Comment by tongueroo** [comment]
Will go out in next release

**Comment by aoozdemir** [comment]
@tongueroo Hah! Amazing. Literally jumped out of the bed at 5 am, once I realised what could have I done instead. :) Thanks a lot. 

Bests.

**Pull request merged**
